### ISSUE TITLE
podspec won't build with vendored_libraries set

### ISSUE THREAD

**Issue by brandonroth** [CocoaPods/cocoapods-packager#91] opened 2015-08-07 19:49 UTC
Using version 1.2.1 I get the the error `[!] podspec has binary-only depedencies, mangling not possible.` If I try again with the --no-mangle option set I get the same error.  If I open the podspec and remove the vendored libraries then everything works.

**Comment by neonichu** [comment] 2015-08-09 16:37
dupe of #71

**Closed by neonichu** 2015-08-09 16:37 UTC
