### ISSUE TITLE
Support for weak-linked frameworks.

### ISSUE THREAD

**Issue by michaelmelanson** [CocoaPods/cocoapods-packager#66] opened 2015-02-18 22:09 UTC
We have a pod which depends on PromiseKit, and that pod has a default subspec (`UIViewController`) that creates a weak link with the `AssetsLibrary` framework. When we run `pod package` on our podspec, the weak linking is dropped and we end up with linker errors when our framework is used.

So far I have worked around this limitation by specifying the exact subspecs I need, to avoid the one that creates the weak link.

Cocoapods-packager should be modified to support weak-linked frameworks such that if your podspec or a dependency's podspec has a `.weak_frameworks` statement, the resulting framework is built with `-weak_framework`.

**Comment by segiddins** [comment] 2015-02-18 22:48
@michaelmelanson shouldn't be too hard to make a quick patch that does that -- just need to aggregate the weak frameworks in the generated framework

**Comment by neonichu** [comment] 2015-02-19 01:26
Is there a public Pod that exhibits this problem or can you share an example? Would make it easier to create an integration spec for this.

**Comment by michaelmelanson** [comment] 2015-02-19 14:08
I agree, this should be a fairly easy fix. I would have done it myself and sent a pull request instead, but I may not have time right away and didn't want it forgotten.

I don't know of any public pods that exhibit this behaviour. But it should be trivial to make one that does: all it needs to do is depend on `PromiseKit`. In the current version anyway (1.2.4), the default subspecs list includes the `UIViewController` subspec which weak-links against AssetsLibrary, triggering the bug. See here: https://github.com/mxcl/PromiseKit/blob/master/PromiseKit.podspec#L118

**Comment by neonichu** [comment] 2015-02-19 14:32
Right, realised that this is actually a duplicate of #48

**Closed by neonichu** 2015-02-19 14:32 UTC

**Comment by neonichu** [comment] 2015-02-19 15:32
@michaelmelanson #48 is fixed now, would appreciate if you could verify if it truly fixes your issue as well.
